FROM nginx:mainline-alpine

WORKDIR /usr/src/app

# copy built files form build stage
COPY --from=ffspb-builder /usr/src/app/www /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
