/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Player, Post } from "ftb-models";
export namespace Components {
    interface FfspbButton {
        "color": 'steel' | 'black' | 'outline';
        "href"?: string;
    }
    interface FfspbCard {
        "href"?: string;
    }
    interface FfspbCardContent {
    }
    interface FfspbCardHead {
    }
    interface FfspbComponentsDemoPage {
    }
    interface FfspbContent {
    }
    interface FfspbContentInner {
    }
    interface FfspbCookiePolicyPage {
    }
    interface FfspbDocsPage {
    }
    interface FfspbFooter {
    }
    interface FfspbGamePage {
    }
    interface FfspbGanePage {
    }
    interface FfspbHeader {
    }
    interface FfspbHealthcheckPage {
    }
    interface FfspbLicenseAgreementPage {
    }
    interface FfspbNews {
    }
    interface FfspbNewsPage {
    }
    interface FfspbPageHead {
    }
    interface FfspbPlayerCareer {
        "player": Player;
    }
    interface FfspbPlayerGames {
        "player": Player;
    }
    interface FfspbPlayerGamesPage {
        "playerId": number;
        "playerName": string;
    }
    interface FfspbPlayerInfo {
        "player": Player;
    }
    interface FfspbPlayerPage {
        "playerId": number;
        "playerName": string;
    }
    interface FfspbPlayerParams {
        "player": Player;
    }
    interface FfspbPlayerStatics {
        "player": Player;
    }
    interface FfspbPostPage {
        "postId": number;
        "postTitle": string;
    }
    interface FfspbRefereePage {
        "refereeId": number;
        "refereeName": string;
    }
    interface FfspbRefereesPage {
    }
    interface FfspbRefereesTrainingPage {
    }
    interface FfspbRoot {
    }
    interface FfspbSeasonCalendarPage {
    }
    interface FfspbSeasonPage {
    }
    interface FfspbSeasonPlayersPage {
    }
    interface FfspbSeasonStadiumsPage {
    }
    interface FfspbSeasonStaffPage {
    }
    interface FfspbSideMenu {
    }
    interface FfspbStadiumPage {
        "stadiumId": number;
    }
    interface FfspbStadiumsPage {
    }
    interface FfspbSwitch {
        "options": [{ key: string; text: string }, { key: string; text: string }];
    }
    interface FfspbTeamGamesPage {
    }
    interface FfspbTeamPage {
    }
    interface FfspbTeamPlayersStatsPage {
    }
    interface FfspbTeamTransfersPage {
    }
    interface FfspbWelcomeBanner {
        "_id": number;
        "bannerTitle": string;
        "isFirstBanner": boolean;
        "isLastBanner": boolean;
        "mode": 'light' | 'dark';
        "text": string;
    }
    interface FfspbWelcomeBanners {
    }
    interface FfspbWelcomeMaterials {
    }
    interface FfspbWelcomeNews {
        "news": Post[];
    }
    interface FfspbWelcomePage {
    }
    interface FfspbWelcomePartners {
    }
    interface FfspbWelcomeTournaments {
    }
}
declare global {
    interface HTMLFfspbButtonElement extends Components.FfspbButton, HTMLStencilElement {
    }
    var HTMLFfspbButtonElement: {
        prototype: HTMLFfspbButtonElement;
        new (): HTMLFfspbButtonElement;
    };
    interface HTMLFfspbCardElement extends Components.FfspbCard, HTMLStencilElement {
    }
    var HTMLFfspbCardElement: {
        prototype: HTMLFfspbCardElement;
        new (): HTMLFfspbCardElement;
    };
    interface HTMLFfspbCardContentElement extends Components.FfspbCardContent, HTMLStencilElement {
    }
    var HTMLFfspbCardContentElement: {
        prototype: HTMLFfspbCardContentElement;
        new (): HTMLFfspbCardContentElement;
    };
    interface HTMLFfspbCardHeadElement extends Components.FfspbCardHead, HTMLStencilElement {
    }
    var HTMLFfspbCardHeadElement: {
        prototype: HTMLFfspbCardHeadElement;
        new (): HTMLFfspbCardHeadElement;
    };
    interface HTMLFfspbComponentsDemoPageElement extends Components.FfspbComponentsDemoPage, HTMLStencilElement {
    }
    var HTMLFfspbComponentsDemoPageElement: {
        prototype: HTMLFfspbComponentsDemoPageElement;
        new (): HTMLFfspbComponentsDemoPageElement;
    };
    interface HTMLFfspbContentElement extends Components.FfspbContent, HTMLStencilElement {
    }
    var HTMLFfspbContentElement: {
        prototype: HTMLFfspbContentElement;
        new (): HTMLFfspbContentElement;
    };
    interface HTMLFfspbContentInnerElement extends Components.FfspbContentInner, HTMLStencilElement {
    }
    var HTMLFfspbContentInnerElement: {
        prototype: HTMLFfspbContentInnerElement;
        new (): HTMLFfspbContentInnerElement;
    };
    interface HTMLFfspbCookiePolicyPageElement extends Components.FfspbCookiePolicyPage, HTMLStencilElement {
    }
    var HTMLFfspbCookiePolicyPageElement: {
        prototype: HTMLFfspbCookiePolicyPageElement;
        new (): HTMLFfspbCookiePolicyPageElement;
    };
    interface HTMLFfspbDocsPageElement extends Components.FfspbDocsPage, HTMLStencilElement {
    }
    var HTMLFfspbDocsPageElement: {
        prototype: HTMLFfspbDocsPageElement;
        new (): HTMLFfspbDocsPageElement;
    };
    interface HTMLFfspbFooterElement extends Components.FfspbFooter, HTMLStencilElement {
    }
    var HTMLFfspbFooterElement: {
        prototype: HTMLFfspbFooterElement;
        new (): HTMLFfspbFooterElement;
    };
    interface HTMLFfspbGamePageElement extends Components.FfspbGamePage, HTMLStencilElement {
    }
    var HTMLFfspbGamePageElement: {
        prototype: HTMLFfspbGamePageElement;
        new (): HTMLFfspbGamePageElement;
    };
    interface HTMLFfspbGanePageElement extends Components.FfspbGanePage, HTMLStencilElement {
    }
    var HTMLFfspbGanePageElement: {
        prototype: HTMLFfspbGanePageElement;
        new (): HTMLFfspbGanePageElement;
    };
    interface HTMLFfspbHeaderElement extends Components.FfspbHeader, HTMLStencilElement {
    }
    var HTMLFfspbHeaderElement: {
        prototype: HTMLFfspbHeaderElement;
        new (): HTMLFfspbHeaderElement;
    };
    interface HTMLFfspbHealthcheckPageElement extends Components.FfspbHealthcheckPage, HTMLStencilElement {
    }
    var HTMLFfspbHealthcheckPageElement: {
        prototype: HTMLFfspbHealthcheckPageElement;
        new (): HTMLFfspbHealthcheckPageElement;
    };
    interface HTMLFfspbLicenseAgreementPageElement extends Components.FfspbLicenseAgreementPage, HTMLStencilElement {
    }
    var HTMLFfspbLicenseAgreementPageElement: {
        prototype: HTMLFfspbLicenseAgreementPageElement;
        new (): HTMLFfspbLicenseAgreementPageElement;
    };
    interface HTMLFfspbNewsElement extends Components.FfspbNews, HTMLStencilElement {
    }
    var HTMLFfspbNewsElement: {
        prototype: HTMLFfspbNewsElement;
        new (): HTMLFfspbNewsElement;
    };
    interface HTMLFfspbNewsPageElement extends Components.FfspbNewsPage, HTMLStencilElement {
    }
    var HTMLFfspbNewsPageElement: {
        prototype: HTMLFfspbNewsPageElement;
        new (): HTMLFfspbNewsPageElement;
    };
    interface HTMLFfspbPageHeadElement extends Components.FfspbPageHead, HTMLStencilElement {
    }
    var HTMLFfspbPageHeadElement: {
        prototype: HTMLFfspbPageHeadElement;
        new (): HTMLFfspbPageHeadElement;
    };
    interface HTMLFfspbPlayerCareerElement extends Components.FfspbPlayerCareer, HTMLStencilElement {
    }
    var HTMLFfspbPlayerCareerElement: {
        prototype: HTMLFfspbPlayerCareerElement;
        new (): HTMLFfspbPlayerCareerElement;
    };
    interface HTMLFfspbPlayerGamesElement extends Components.FfspbPlayerGames, HTMLStencilElement {
    }
    var HTMLFfspbPlayerGamesElement: {
        prototype: HTMLFfspbPlayerGamesElement;
        new (): HTMLFfspbPlayerGamesElement;
    };
    interface HTMLFfspbPlayerGamesPageElement extends Components.FfspbPlayerGamesPage, HTMLStencilElement {
    }
    var HTMLFfspbPlayerGamesPageElement: {
        prototype: HTMLFfspbPlayerGamesPageElement;
        new (): HTMLFfspbPlayerGamesPageElement;
    };
    interface HTMLFfspbPlayerInfoElement extends Components.FfspbPlayerInfo, HTMLStencilElement {
    }
    var HTMLFfspbPlayerInfoElement: {
        prototype: HTMLFfspbPlayerInfoElement;
        new (): HTMLFfspbPlayerInfoElement;
    };
    interface HTMLFfspbPlayerPageElement extends Components.FfspbPlayerPage, HTMLStencilElement {
    }
    var HTMLFfspbPlayerPageElement: {
        prototype: HTMLFfspbPlayerPageElement;
        new (): HTMLFfspbPlayerPageElement;
    };
    interface HTMLFfspbPlayerParamsElement extends Components.FfspbPlayerParams, HTMLStencilElement {
    }
    var HTMLFfspbPlayerParamsElement: {
        prototype: HTMLFfspbPlayerParamsElement;
        new (): HTMLFfspbPlayerParamsElement;
    };
    interface HTMLFfspbPlayerStaticsElement extends Components.FfspbPlayerStatics, HTMLStencilElement {
    }
    var HTMLFfspbPlayerStaticsElement: {
        prototype: HTMLFfspbPlayerStaticsElement;
        new (): HTMLFfspbPlayerStaticsElement;
    };
    interface HTMLFfspbPostPageElement extends Components.FfspbPostPage, HTMLStencilElement {
    }
    var HTMLFfspbPostPageElement: {
        prototype: HTMLFfspbPostPageElement;
        new (): HTMLFfspbPostPageElement;
    };
    interface HTMLFfspbRefereePageElement extends Components.FfspbRefereePage, HTMLStencilElement {
    }
    var HTMLFfspbRefereePageElement: {
        prototype: HTMLFfspbRefereePageElement;
        new (): HTMLFfspbRefereePageElement;
    };
    interface HTMLFfspbRefereesPageElement extends Components.FfspbRefereesPage, HTMLStencilElement {
    }
    var HTMLFfspbRefereesPageElement: {
        prototype: HTMLFfspbRefereesPageElement;
        new (): HTMLFfspbRefereesPageElement;
    };
    interface HTMLFfspbRefereesTrainingPageElement extends Components.FfspbRefereesTrainingPage, HTMLStencilElement {
    }
    var HTMLFfspbRefereesTrainingPageElement: {
        prototype: HTMLFfspbRefereesTrainingPageElement;
        new (): HTMLFfspbRefereesTrainingPageElement;
    };
    interface HTMLFfspbRootElement extends Components.FfspbRoot, HTMLStencilElement {
    }
    var HTMLFfspbRootElement: {
        prototype: HTMLFfspbRootElement;
        new (): HTMLFfspbRootElement;
    };
    interface HTMLFfspbSeasonCalendarPageElement extends Components.FfspbSeasonCalendarPage, HTMLStencilElement {
    }
    var HTMLFfspbSeasonCalendarPageElement: {
        prototype: HTMLFfspbSeasonCalendarPageElement;
        new (): HTMLFfspbSeasonCalendarPageElement;
    };
    interface HTMLFfspbSeasonPageElement extends Components.FfspbSeasonPage, HTMLStencilElement {
    }
    var HTMLFfspbSeasonPageElement: {
        prototype: HTMLFfspbSeasonPageElement;
        new (): HTMLFfspbSeasonPageElement;
    };
    interface HTMLFfspbSeasonPlayersPageElement extends Components.FfspbSeasonPlayersPage, HTMLStencilElement {
    }
    var HTMLFfspbSeasonPlayersPageElement: {
        prototype: HTMLFfspbSeasonPlayersPageElement;
        new (): HTMLFfspbSeasonPlayersPageElement;
    };
    interface HTMLFfspbSeasonStadiumsPageElement extends Components.FfspbSeasonStadiumsPage, HTMLStencilElement {
    }
    var HTMLFfspbSeasonStadiumsPageElement: {
        prototype: HTMLFfspbSeasonStadiumsPageElement;
        new (): HTMLFfspbSeasonStadiumsPageElement;
    };
    interface HTMLFfspbSeasonStaffPageElement extends Components.FfspbSeasonStaffPage, HTMLStencilElement {
    }
    var HTMLFfspbSeasonStaffPageElement: {
        prototype: HTMLFfspbSeasonStaffPageElement;
        new (): HTMLFfspbSeasonStaffPageElement;
    };
    interface HTMLFfspbSideMenuElement extends Components.FfspbSideMenu, HTMLStencilElement {
    }
    var HTMLFfspbSideMenuElement: {
        prototype: HTMLFfspbSideMenuElement;
        new (): HTMLFfspbSideMenuElement;
    };
    interface HTMLFfspbStadiumPageElement extends Components.FfspbStadiumPage, HTMLStencilElement {
    }
    var HTMLFfspbStadiumPageElement: {
        prototype: HTMLFfspbStadiumPageElement;
        new (): HTMLFfspbStadiumPageElement;
    };
    interface HTMLFfspbStadiumsPageElement extends Components.FfspbStadiumsPage, HTMLStencilElement {
    }
    var HTMLFfspbStadiumsPageElement: {
        prototype: HTMLFfspbStadiumsPageElement;
        new (): HTMLFfspbStadiumsPageElement;
    };
    interface HTMLFfspbSwitchElement extends Components.FfspbSwitch, HTMLStencilElement {
    }
    var HTMLFfspbSwitchElement: {
        prototype: HTMLFfspbSwitchElement;
        new (): HTMLFfspbSwitchElement;
    };
    interface HTMLFfspbTeamGamesPageElement extends Components.FfspbTeamGamesPage, HTMLStencilElement {
    }
    var HTMLFfspbTeamGamesPageElement: {
        prototype: HTMLFfspbTeamGamesPageElement;
        new (): HTMLFfspbTeamGamesPageElement;
    };
    interface HTMLFfspbTeamPageElement extends Components.FfspbTeamPage, HTMLStencilElement {
    }
    var HTMLFfspbTeamPageElement: {
        prototype: HTMLFfspbTeamPageElement;
        new (): HTMLFfspbTeamPageElement;
    };
    interface HTMLFfspbTeamPlayersStatsPageElement extends Components.FfspbTeamPlayersStatsPage, HTMLStencilElement {
    }
    var HTMLFfspbTeamPlayersStatsPageElement: {
        prototype: HTMLFfspbTeamPlayersStatsPageElement;
        new (): HTMLFfspbTeamPlayersStatsPageElement;
    };
    interface HTMLFfspbTeamTransfersPageElement extends Components.FfspbTeamTransfersPage, HTMLStencilElement {
    }
    var HTMLFfspbTeamTransfersPageElement: {
        prototype: HTMLFfspbTeamTransfersPageElement;
        new (): HTMLFfspbTeamTransfersPageElement;
    };
    interface HTMLFfspbWelcomeBannerElement extends Components.FfspbWelcomeBanner, HTMLStencilElement {
    }
    var HTMLFfspbWelcomeBannerElement: {
        prototype: HTMLFfspbWelcomeBannerElement;
        new (): HTMLFfspbWelcomeBannerElement;
    };
    interface HTMLFfspbWelcomeBannersElement extends Components.FfspbWelcomeBanners, HTMLStencilElement {
    }
    var HTMLFfspbWelcomeBannersElement: {
        prototype: HTMLFfspbWelcomeBannersElement;
        new (): HTMLFfspbWelcomeBannersElement;
    };
    interface HTMLFfspbWelcomeMaterialsElement extends Components.FfspbWelcomeMaterials, HTMLStencilElement {
    }
    var HTMLFfspbWelcomeMaterialsElement: {
        prototype: HTMLFfspbWelcomeMaterialsElement;
        new (): HTMLFfspbWelcomeMaterialsElement;
    };
    interface HTMLFfspbWelcomeNewsElement extends Components.FfspbWelcomeNews, HTMLStencilElement {
    }
    var HTMLFfspbWelcomeNewsElement: {
        prototype: HTMLFfspbWelcomeNewsElement;
        new (): HTMLFfspbWelcomeNewsElement;
    };
    interface HTMLFfspbWelcomePageElement extends Components.FfspbWelcomePage, HTMLStencilElement {
    }
    var HTMLFfspbWelcomePageElement: {
        prototype: HTMLFfspbWelcomePageElement;
        new (): HTMLFfspbWelcomePageElement;
    };
    interface HTMLFfspbWelcomePartnersElement extends Components.FfspbWelcomePartners, HTMLStencilElement {
    }
    var HTMLFfspbWelcomePartnersElement: {
        prototype: HTMLFfspbWelcomePartnersElement;
        new (): HTMLFfspbWelcomePartnersElement;
    };
    interface HTMLFfspbWelcomeTournamentsElement extends Components.FfspbWelcomeTournaments, HTMLStencilElement {
    }
    var HTMLFfspbWelcomeTournamentsElement: {
        prototype: HTMLFfspbWelcomeTournamentsElement;
        new (): HTMLFfspbWelcomeTournamentsElement;
    };
    interface HTMLElementTagNameMap {
        "ffspb-button": HTMLFfspbButtonElement;
        "ffspb-card": HTMLFfspbCardElement;
        "ffspb-card-content": HTMLFfspbCardContentElement;
        "ffspb-card-head": HTMLFfspbCardHeadElement;
        "ffspb-components-demo-page": HTMLFfspbComponentsDemoPageElement;
        "ffspb-content": HTMLFfspbContentElement;
        "ffspb-content-inner": HTMLFfspbContentInnerElement;
        "ffspb-cookie-policy-page": HTMLFfspbCookiePolicyPageElement;
        "ffspb-docs-page": HTMLFfspbDocsPageElement;
        "ffspb-footer": HTMLFfspbFooterElement;
        "ffspb-game-page": HTMLFfspbGamePageElement;
        "ffspb-gane-page": HTMLFfspbGanePageElement;
        "ffspb-header": HTMLFfspbHeaderElement;
        "ffspb-healthcheck-page": HTMLFfspbHealthcheckPageElement;
        "ffspb-license-agreement-page": HTMLFfspbLicenseAgreementPageElement;
        "ffspb-news": HTMLFfspbNewsElement;
        "ffspb-news-page": HTMLFfspbNewsPageElement;
        "ffspb-page-head": HTMLFfspbPageHeadElement;
        "ffspb-player-career": HTMLFfspbPlayerCareerElement;
        "ffspb-player-games": HTMLFfspbPlayerGamesElement;
        "ffspb-player-games-page": HTMLFfspbPlayerGamesPageElement;
        "ffspb-player-info": HTMLFfspbPlayerInfoElement;
        "ffspb-player-page": HTMLFfspbPlayerPageElement;
        "ffspb-player-params": HTMLFfspbPlayerParamsElement;
        "ffspb-player-statics": HTMLFfspbPlayerStaticsElement;
        "ffspb-post-page": HTMLFfspbPostPageElement;
        "ffspb-referee-page": HTMLFfspbRefereePageElement;
        "ffspb-referees-page": HTMLFfspbRefereesPageElement;
        "ffspb-referees-training-page": HTMLFfspbRefereesTrainingPageElement;
        "ffspb-root": HTMLFfspbRootElement;
        "ffspb-season-calendar-page": HTMLFfspbSeasonCalendarPageElement;
        "ffspb-season-page": HTMLFfspbSeasonPageElement;
        "ffspb-season-players-page": HTMLFfspbSeasonPlayersPageElement;
        "ffspb-season-stadiums-page": HTMLFfspbSeasonStadiumsPageElement;
        "ffspb-season-staff-page": HTMLFfspbSeasonStaffPageElement;
        "ffspb-side-menu": HTMLFfspbSideMenuElement;
        "ffspb-stadium-page": HTMLFfspbStadiumPageElement;
        "ffspb-stadiums-page": HTMLFfspbStadiumsPageElement;
        "ffspb-switch": HTMLFfspbSwitchElement;
        "ffspb-team-games-page": HTMLFfspbTeamGamesPageElement;
        "ffspb-team-page": HTMLFfspbTeamPageElement;
        "ffspb-team-players-stats-page": HTMLFfspbTeamPlayersStatsPageElement;
        "ffspb-team-transfers-page": HTMLFfspbTeamTransfersPageElement;
        "ffspb-welcome-banner": HTMLFfspbWelcomeBannerElement;
        "ffspb-welcome-banners": HTMLFfspbWelcomeBannersElement;
        "ffspb-welcome-materials": HTMLFfspbWelcomeMaterialsElement;
        "ffspb-welcome-news": HTMLFfspbWelcomeNewsElement;
        "ffspb-welcome-page": HTMLFfspbWelcomePageElement;
        "ffspb-welcome-partners": HTMLFfspbWelcomePartnersElement;
        "ffspb-welcome-tournaments": HTMLFfspbWelcomeTournamentsElement;
    }
}
declare namespace LocalJSX {
    interface FfspbButton {
        "color"?: 'steel' | 'black' | 'outline';
        "href"?: string;
    }
    interface FfspbCard {
        "href"?: string;
    }
    interface FfspbCardContent {
    }
    interface FfspbCardHead {
    }
    interface FfspbComponentsDemoPage {
    }
    interface FfspbContent {
    }
    interface FfspbContentInner {
    }
    interface FfspbCookiePolicyPage {
    }
    interface FfspbDocsPage {
    }
    interface FfspbFooter {
    }
    interface FfspbGamePage {
    }
    interface FfspbGanePage {
    }
    interface FfspbHeader {
    }
    interface FfspbHealthcheckPage {
    }
    interface FfspbLicenseAgreementPage {
    }
    interface FfspbNews {
    }
    interface FfspbNewsPage {
    }
    interface FfspbPageHead {
    }
    interface FfspbPlayerCareer {
        "player"?: Player;
    }
    interface FfspbPlayerGames {
        "player"?: Player;
    }
    interface FfspbPlayerGamesPage {
        "playerId"?: number;
        "playerName"?: string;
    }
    interface FfspbPlayerInfo {
        "player"?: Player;
    }
    interface FfspbPlayerPage {
        "playerId"?: number;
        "playerName"?: string;
    }
    interface FfspbPlayerParams {
        "player"?: Player;
    }
    interface FfspbPlayerStatics {
        "player"?: Player;
    }
    interface FfspbPostPage {
        "postId"?: number;
        "postTitle"?: string;
    }
    interface FfspbRefereePage {
        "refereeId"?: number;
        "refereeName"?: string;
    }
    interface FfspbRefereesPage {
    }
    interface FfspbRefereesTrainingPage {
    }
    interface FfspbRoot {
    }
    interface FfspbSeasonCalendarPage {
    }
    interface FfspbSeasonPage {
    }
    interface FfspbSeasonPlayersPage {
    }
    interface FfspbSeasonStadiumsPage {
    }
    interface FfspbSeasonStaffPage {
    }
    interface FfspbSideMenu {
    }
    interface FfspbStadiumPage {
        "stadiumId"?: number;
    }
    interface FfspbStadiumsPage {
    }
    interface FfspbSwitch {
        "onSelected"?: (event: CustomEvent<{ key: string; text: string }>) => void;
        "options": [{ key: string; text: string }, { key: string; text: string }];
    }
    interface FfspbTeamGamesPage {
    }
    interface FfspbTeamPage {
    }
    interface FfspbTeamPlayersStatsPage {
    }
    interface FfspbTeamTransfersPage {
    }
    interface FfspbWelcomeBanner {
        "_id": number;
        "bannerTitle": string;
        "isFirstBanner"?: boolean;
        "isLastBanner"?: boolean;
        "mode"?: 'light' | 'dark';
        "text": string;
    }
    interface FfspbWelcomeBanners {
    }
    interface FfspbWelcomeMaterials {
    }
    interface FfspbWelcomeNews {
        "news"?: Post[];
    }
    interface FfspbWelcomePage {
    }
    interface FfspbWelcomePartners {
    }
    interface FfspbWelcomeTournaments {
    }
    interface IntrinsicElements {
        "ffspb-button": FfspbButton;
        "ffspb-card": FfspbCard;
        "ffspb-card-content": FfspbCardContent;
        "ffspb-card-head": FfspbCardHead;
        "ffspb-components-demo-page": FfspbComponentsDemoPage;
        "ffspb-content": FfspbContent;
        "ffspb-content-inner": FfspbContentInner;
        "ffspb-cookie-policy-page": FfspbCookiePolicyPage;
        "ffspb-docs-page": FfspbDocsPage;
        "ffspb-footer": FfspbFooter;
        "ffspb-game-page": FfspbGamePage;
        "ffspb-gane-page": FfspbGanePage;
        "ffspb-header": FfspbHeader;
        "ffspb-healthcheck-page": FfspbHealthcheckPage;
        "ffspb-license-agreement-page": FfspbLicenseAgreementPage;
        "ffspb-news": FfspbNews;
        "ffspb-news-page": FfspbNewsPage;
        "ffspb-page-head": FfspbPageHead;
        "ffspb-player-career": FfspbPlayerCareer;
        "ffspb-player-games": FfspbPlayerGames;
        "ffspb-player-games-page": FfspbPlayerGamesPage;
        "ffspb-player-info": FfspbPlayerInfo;
        "ffspb-player-page": FfspbPlayerPage;
        "ffspb-player-params": FfspbPlayerParams;
        "ffspb-player-statics": FfspbPlayerStatics;
        "ffspb-post-page": FfspbPostPage;
        "ffspb-referee-page": FfspbRefereePage;
        "ffspb-referees-page": FfspbRefereesPage;
        "ffspb-referees-training-page": FfspbRefereesTrainingPage;
        "ffspb-root": FfspbRoot;
        "ffspb-season-calendar-page": FfspbSeasonCalendarPage;
        "ffspb-season-page": FfspbSeasonPage;
        "ffspb-season-players-page": FfspbSeasonPlayersPage;
        "ffspb-season-stadiums-page": FfspbSeasonStadiumsPage;
        "ffspb-season-staff-page": FfspbSeasonStaffPage;
        "ffspb-side-menu": FfspbSideMenu;
        "ffspb-stadium-page": FfspbStadiumPage;
        "ffspb-stadiums-page": FfspbStadiumsPage;
        "ffspb-switch": FfspbSwitch;
        "ffspb-team-games-page": FfspbTeamGamesPage;
        "ffspb-team-page": FfspbTeamPage;
        "ffspb-team-players-stats-page": FfspbTeamPlayersStatsPage;
        "ffspb-team-transfers-page": FfspbTeamTransfersPage;
        "ffspb-welcome-banner": FfspbWelcomeBanner;
        "ffspb-welcome-banners": FfspbWelcomeBanners;
        "ffspb-welcome-materials": FfspbWelcomeMaterials;
        "ffspb-welcome-news": FfspbWelcomeNews;
        "ffspb-welcome-page": FfspbWelcomePage;
        "ffspb-welcome-partners": FfspbWelcomePartners;
        "ffspb-welcome-tournaments": FfspbWelcomeTournaments;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ffspb-button": LocalJSX.FfspbButton & JSXBase.HTMLAttributes<HTMLFfspbButtonElement>;
            "ffspb-card": LocalJSX.FfspbCard & JSXBase.HTMLAttributes<HTMLFfspbCardElement>;
            "ffspb-card-content": LocalJSX.FfspbCardContent & JSXBase.HTMLAttributes<HTMLFfspbCardContentElement>;
            "ffspb-card-head": LocalJSX.FfspbCardHead & JSXBase.HTMLAttributes<HTMLFfspbCardHeadElement>;
            "ffspb-components-demo-page": LocalJSX.FfspbComponentsDemoPage & JSXBase.HTMLAttributes<HTMLFfspbComponentsDemoPageElement>;
            "ffspb-content": LocalJSX.FfspbContent & JSXBase.HTMLAttributes<HTMLFfspbContentElement>;
            "ffspb-content-inner": LocalJSX.FfspbContentInner & JSXBase.HTMLAttributes<HTMLFfspbContentInnerElement>;
            "ffspb-cookie-policy-page": LocalJSX.FfspbCookiePolicyPage & JSXBase.HTMLAttributes<HTMLFfspbCookiePolicyPageElement>;
            "ffspb-docs-page": LocalJSX.FfspbDocsPage & JSXBase.HTMLAttributes<HTMLFfspbDocsPageElement>;
            "ffspb-footer": LocalJSX.FfspbFooter & JSXBase.HTMLAttributes<HTMLFfspbFooterElement>;
            "ffspb-game-page": LocalJSX.FfspbGamePage & JSXBase.HTMLAttributes<HTMLFfspbGamePageElement>;
            "ffspb-gane-page": LocalJSX.FfspbGanePage & JSXBase.HTMLAttributes<HTMLFfspbGanePageElement>;
            "ffspb-header": LocalJSX.FfspbHeader & JSXBase.HTMLAttributes<HTMLFfspbHeaderElement>;
            "ffspb-healthcheck-page": LocalJSX.FfspbHealthcheckPage & JSXBase.HTMLAttributes<HTMLFfspbHealthcheckPageElement>;
            "ffspb-license-agreement-page": LocalJSX.FfspbLicenseAgreementPage & JSXBase.HTMLAttributes<HTMLFfspbLicenseAgreementPageElement>;
            "ffspb-news": LocalJSX.FfspbNews & JSXBase.HTMLAttributes<HTMLFfspbNewsElement>;
            "ffspb-news-page": LocalJSX.FfspbNewsPage & JSXBase.HTMLAttributes<HTMLFfspbNewsPageElement>;
            "ffspb-page-head": LocalJSX.FfspbPageHead & JSXBase.HTMLAttributes<HTMLFfspbPageHeadElement>;
            "ffspb-player-career": LocalJSX.FfspbPlayerCareer & JSXBase.HTMLAttributes<HTMLFfspbPlayerCareerElement>;
            "ffspb-player-games": LocalJSX.FfspbPlayerGames & JSXBase.HTMLAttributes<HTMLFfspbPlayerGamesElement>;
            "ffspb-player-games-page": LocalJSX.FfspbPlayerGamesPage & JSXBase.HTMLAttributes<HTMLFfspbPlayerGamesPageElement>;
            "ffspb-player-info": LocalJSX.FfspbPlayerInfo & JSXBase.HTMLAttributes<HTMLFfspbPlayerInfoElement>;
            "ffspb-player-page": LocalJSX.FfspbPlayerPage & JSXBase.HTMLAttributes<HTMLFfspbPlayerPageElement>;
            "ffspb-player-params": LocalJSX.FfspbPlayerParams & JSXBase.HTMLAttributes<HTMLFfspbPlayerParamsElement>;
            "ffspb-player-statics": LocalJSX.FfspbPlayerStatics & JSXBase.HTMLAttributes<HTMLFfspbPlayerStaticsElement>;
            "ffspb-post-page": LocalJSX.FfspbPostPage & JSXBase.HTMLAttributes<HTMLFfspbPostPageElement>;
            "ffspb-referee-page": LocalJSX.FfspbRefereePage & JSXBase.HTMLAttributes<HTMLFfspbRefereePageElement>;
            "ffspb-referees-page": LocalJSX.FfspbRefereesPage & JSXBase.HTMLAttributes<HTMLFfspbRefereesPageElement>;
            "ffspb-referees-training-page": LocalJSX.FfspbRefereesTrainingPage & JSXBase.HTMLAttributes<HTMLFfspbRefereesTrainingPageElement>;
            "ffspb-root": LocalJSX.FfspbRoot & JSXBase.HTMLAttributes<HTMLFfspbRootElement>;
            "ffspb-season-calendar-page": LocalJSX.FfspbSeasonCalendarPage & JSXBase.HTMLAttributes<HTMLFfspbSeasonCalendarPageElement>;
            "ffspb-season-page": LocalJSX.FfspbSeasonPage & JSXBase.HTMLAttributes<HTMLFfspbSeasonPageElement>;
            "ffspb-season-players-page": LocalJSX.FfspbSeasonPlayersPage & JSXBase.HTMLAttributes<HTMLFfspbSeasonPlayersPageElement>;
            "ffspb-season-stadiums-page": LocalJSX.FfspbSeasonStadiumsPage & JSXBase.HTMLAttributes<HTMLFfspbSeasonStadiumsPageElement>;
            "ffspb-season-staff-page": LocalJSX.FfspbSeasonStaffPage & JSXBase.HTMLAttributes<HTMLFfspbSeasonStaffPageElement>;
            "ffspb-side-menu": LocalJSX.FfspbSideMenu & JSXBase.HTMLAttributes<HTMLFfspbSideMenuElement>;
            "ffspb-stadium-page": LocalJSX.FfspbStadiumPage & JSXBase.HTMLAttributes<HTMLFfspbStadiumPageElement>;
            "ffspb-stadiums-page": LocalJSX.FfspbStadiumsPage & JSXBase.HTMLAttributes<HTMLFfspbStadiumsPageElement>;
            "ffspb-switch": LocalJSX.FfspbSwitch & JSXBase.HTMLAttributes<HTMLFfspbSwitchElement>;
            "ffspb-team-games-page": LocalJSX.FfspbTeamGamesPage & JSXBase.HTMLAttributes<HTMLFfspbTeamGamesPageElement>;
            "ffspb-team-page": LocalJSX.FfspbTeamPage & JSXBase.HTMLAttributes<HTMLFfspbTeamPageElement>;
            "ffspb-team-players-stats-page": LocalJSX.FfspbTeamPlayersStatsPage & JSXBase.HTMLAttributes<HTMLFfspbTeamPlayersStatsPageElement>;
            "ffspb-team-transfers-page": LocalJSX.FfspbTeamTransfersPage & JSXBase.HTMLAttributes<HTMLFfspbTeamTransfersPageElement>;
            "ffspb-welcome-banner": LocalJSX.FfspbWelcomeBanner & JSXBase.HTMLAttributes<HTMLFfspbWelcomeBannerElement>;
            "ffspb-welcome-banners": LocalJSX.FfspbWelcomeBanners & JSXBase.HTMLAttributes<HTMLFfspbWelcomeBannersElement>;
            "ffspb-welcome-materials": LocalJSX.FfspbWelcomeMaterials & JSXBase.HTMLAttributes<HTMLFfspbWelcomeMaterialsElement>;
            "ffspb-welcome-news": LocalJSX.FfspbWelcomeNews & JSXBase.HTMLAttributes<HTMLFfspbWelcomeNewsElement>;
            "ffspb-welcome-page": LocalJSX.FfspbWelcomePage & JSXBase.HTMLAttributes<HTMLFfspbWelcomePageElement>;
            "ffspb-welcome-partners": LocalJSX.FfspbWelcomePartners & JSXBase.HTMLAttributes<HTMLFfspbWelcomePartnersElement>;
            "ffspb-welcome-tournaments": LocalJSX.FfspbWelcomeTournaments & JSXBase.HTMLAttributes<HTMLFfspbWelcomeTournamentsElement>;
        }
    }
}
